using Deguffer.Core.Execution;
using Deguffer.Core.Safety;
using Deguffer.Core.Scanning;

namespace Deguffer.Core.Providers;

/// <summary>
/// vcpkg's binary cache and the scratch directories its builds leave behind. Researched rather than
/// measured: no vcpkg installation was present on the machine this was written against.
///
/// <para><b>Tier 2, because restoring one of these is a compile rather than a download.</b> vcpkg
/// builds every port from source, and the binary cache is what stops it doing that twice. Deleting
/// an entry costs the next install the whole build of that library, which for something the size of
/// Boost or Qt is tens of minutes to hours — §3's "re-created, but only by re-downloading gigabytes
/// or re-indexing for minutes", with the clock running the other way. Two of the four directories
/// here are genuinely scratch and would be Tier 1 alone, but a plan carries one tier and the more
/// cautious of the two governs it. The user is never denied them: selection is per step, so the
/// scratch can be taken and the cache left.</para>
///
/// <para><b>§5.1 was asked and there is no eviction command.</b> vcpkg's own answer to a cache that
/// has grown too large is the <c>--clean-after-build</c> family of flags on <c>vcpkg install</c>,
/// which cleans as it goes rather than afterwards, and its documentation says outright that
/// <c>buildtrees</c>, <c>downloads</c> and <c>packages</c> under the root are safe to delete. So
/// path deletion here is the vendor's own recommendation rather than a workaround.</para>
///
/// <para><b>This provider may see one location or four, and it says which.</b> The binary cache is
/// in the user's profile and is findable on any machine. The other three live inside the vcpkg
/// clone — a git checkout the user put wherever they liked — which is knowable only from
/// <c>VCPKG_ROOT</c>, from the file <c>vcpkg integrate install</c> wrote, or from the executable on
/// <c>PATH</c>. Where none of those answers, the plan carries a sentence saying so. A provider that
/// silently reported a fraction of a cache would be worse than one that names the part it could not
/// reach.</para>
///
/// <para><b>§5.2's trap here is the largest directory of the lot.</b> <c>installed</c> sits in the
/// same root as the three scratch directories, it is regenerated by exactly the command that fills
/// them, and it is what every project on the machine links against. It is never enumerated and
/// never a target — this provider names the paths it removes rather than listing the clone, which
/// is what <see cref="DeclaredRoot"/> is for — and it is a named survivor, so a run produces
/// evidence rather than an absence of mention.</para>
/// </summary>
public sealed class VcpkgCacheProvider : CleanupProviderBase
{
    /// <summary>
    /// What the vcpkg clone holds that must survive a rule reaching into it. <c>installed</c> is
    /// the reason this list exists; the rest are the clone itself, and losing any of them means
    /// re-cloning rather than rebuilding.
    /// </summary>
    private static readonly (string RelativePath, string Reason)[] ProtectedInRoot =
    [
        ("installed", "The libraries vcpkg has installed, which every project on this machine links against."),
        ("ports", "The port definitions this clone builds from."),
        ("triplets", "The triplet definitions, including any the user wrote."),
        ("versions", "The registry's version database."),
        ("scripts", "vcpkg's own build scripts."),
        ("vcpkg.exe", "The vcpkg executable itself, which the bootstrap built into this directory."),
    ];

    /// <summary>
    /// What the user's vcpkg directory holds beside the binary cache. Both are small, and both are
    /// records rather than caches: one says where the clone is, and the other holds the registry
    /// clones a manifest resolves against.
    /// </summary>
    private static readonly (string RelativePath, string Reason)[] ProtectedInProfile =
    [
        (VcpkgDiscovery.IntegrationFile, "vcpkg's record of which clone is integrated with Visual Studio."),
        ("registries", "Clones of the registries a manifest resolves versions against."),
    ];

    private readonly VcpkgDiscovery _discovery;

    private VcpkgLocations? _located;

    public VcpkgCacheProvider(
        IUserEnvironment? environment = null,
        IProcessRunner? runner = null,
        IProcessInspector? inspector = null,
        IDirectoryScanner? scanner = null)
        : base(
            environment ?? UserEnvironment.Current,
            runner ?? ProcessRunner.Default,
            inspector ?? ProcessInspector.Default,
            scanner ?? DirectoryScanner.Default)
        => _discovery = new VcpkgDiscovery(Environment);

    public override string Id => "vcpkg";

    public override string Name => "vcpkg build caches";

    public override SafetyTier Tier => SafetyTier.RegenerableWithCost;

    public override string WhatHappensOnNextUse =>
        "The next vcpkg install rebuilds the affected libraries from source instead of unpacking a "
        + "cached binary, which for a large library is tens of minutes, and downloads their source "
        + "archives again as it goes. Libraries already installed stay installed, and the ports, "
        + "triplets and registries are untouched.";

    /// <summary>
    /// Whose files these are and what they are for. See <see cref="ProviderDescription"/>.
    /// </summary>
    public override ProviderDescription Description { get; } = new()
    {
        Application = "vcpkg, a package manager for C and C++ libraries",
        Publisher = "Microsoft",
        Purpose = "vcpkg builds every library from source. The binary cache keeps the result so "
            + "it need not build the same one twice, and the downloads, buildtrees and packages "
            + "folders inside the vcpkg clone hold the sources and the scratch each build left "
            + "behind.",
        Recommendation = "Only when you need the space. Restoring a cached entry is a compile "
            + "rather than a download, and for something the size of Boost or Qt that is tens of "
            + "minutes to hours. The installed folder every project links against is never "
            + "touched.",
    };

    /// <summary>
    /// §5.3. Only vcpkg's own name, deliberately: the compilers and build tools it drives are the
    /// user's everyday ones, so warning on those would fire on almost every scan, and a warning
    /// that is always there is one nobody reads.
    /// </summary>
    protected override IReadOnlyList<string> ConflictingProcessNames => ["vcpkg"];

    /// <summary>
    /// Where vcpkg's directories are on this machine, memoised for the life of a planning pass (G4).
    /// Presence and planning ask the same question of the same disk, and answering it reads an
    /// environment, probes two directories and may open a file.
    ///
    /// Exposed so tests can assert what is reached.
    /// </summary>
    public VcpkgLocations Locate() => _located ??= _discovery.Discover();

    /// <summary>
    /// Every one of those answers is configuration — three environment variables, a file vcpkg
    /// writes, and what is on <c>PATH</c> — so a remembered location would measure a directory
    /// vcpkg has stopped using.
    /// </summary>
    public override void InvalidateCaches()
    {
        _located = null;
        base.InvalidateCaches();
    }

    /// <summary>
    /// Presence is a declared path actually being there. The user's vcpkg directory exists on any
    /// machine that has ever integrated vcpkg with Visual Studio, and reading that as a hit would
    /// report a source the plan then has nothing to say about.
    /// </summary>
    /// <summary>
    /// §5.2 as §7.1 needs it read from outside. Both of the user's vcpkg directories, because the
    /// documented search order for the binary cache falls through from the local profile to the
    /// roaming one, and a cache found under the second still has that second directory's own records
    /// beside it.
    ///
    /// <para>The clone is deliberately absent. Finding it reads three environment variables, probes
    /// for a marker file and searches <c>PATH</c>, and a declaration Explore consults on every path
    /// has to be readable without any of that. Nothing under a clone is refused here as a result,
    /// which is why this provider still names <c>installed</c> a survivor in its own plan.</para>
    /// </summary>
    public override IReadOnlyList<ToolRoot> ToolRoots =>
    [
        .. _discovery.ProfileDirectories.Select(profile => new ToolRoot(
            profile,
            "This is your vcpkg folder. Deguffer removes the binary cache inside it and nothing "
            + "else, because the record of which vcpkg clone is integrated and the registry clones "
            + "a manifest resolves versions against both sit beside that cache.",
            static name => name.Equals("archives", StringComparison.OrdinalIgnoreCase))),
    ];

    public override Task<bool> IsPresentAsync(CancellationToken ct = default) =>
        Task.FromResult(DeclaredPaths(Declare(Locate())).Any(LongPath.DirectoryExists));

    public override async Task<CleanupPlan> PlanAsync(CancellationToken ct = default)
    {
        var located = Locate();
        var refused = new List<string>();
        var scan = DeclaredLocations.Examine(Declare(located, refused), ct);

        if (scan.FoundNothing)
        {
            return EmptyPlan(
                refused.Count > 0 ? RefusedSentence(refused[0])
                : located.UnmarkedRoot is { } nothingFound ? UnmarkedRootSentence(nothingFound)
                : "vcpkg has cached nothing on this machine.");
        }

        var notes = new List<PlanNote>(scan.Notes);

        // A refusal is said out loud, for the reason the unmarked root is: the user pointed a
        // variable at a directory and it is not in the plan, and a number with nothing explaining it
        // is how a user concludes Deguffer is broken rather than careful.
        notes.AddRange(refused.Select(path =>
            new PlanNote(PlanNoteSeverity.Information, RefusedSentence(path))));

        if (located.Root is null)
        {
            // Said whenever the clone was not reached, not only when something was reclaimed without
            // it. The user is looking at a number, and the number is a quarter of the subject. Which
            // sentence they get matters: telling somebody to set a variable they have already set
            // sends them looking for a mistake they did not make.
            notes.Add(new PlanNote(
                PlanNoteSeverity.Information,
                located.UnmarkedRoot is { } declined
                    ? UnmarkedRootSentence(declined)
                    : "This covers the binary cache only. vcpkg's own directory is a clone that can be "
                      + $"anywhere, and Deguffer could not find it — set {VcpkgDiscovery.RootVariable}, or "
                      + "put vcpkg on PATH, and the buildtrees, downloads and packages directories inside "
                      + "it are covered too."));
        }

        var (steps, measured) = await PlanDeletionsAsync(scan.Targets, ct).ConfigureAwait(false);

        if (measured.Note is { } scanNote)
        {
            notes.Add(scanNote);
        }

        if (BuildRunningProcessNote() is { } warning)
        {
            notes.Add(warning);
        }

        return new CleanupPlan
        {
            ProviderId = Id,
            ProviderName = Name,
            Tier = Tier,
            WhatHappensOnNextUse = WhatHappensOnNextUse,
            Steps = steps,
            ProtectedPaths = Protect([.. scan.Protected]),
            Notes = notes,
            Fallback = measured.Fallback,
        };
    }

    /// <summary>
    /// What the user is told when something named a clone and Deguffer declined it. It names the
    /// directory and the marker, because "could not find it" would be untrue and the advice that
    /// sentence goes on to give has already been taken.
    /// </summary>
    /// <summary>
    /// What the user is told when a variable named something that is not a cache to remove.
    /// </summary>
    private static string RefusedSentence(string path) =>
        $"Leaving '{path}' alone: that is vcpkg's own directory, or something inside it Deguffer "
        + "never removes, rather than a cache. A variable can say where a cache is. It cannot ask "
        + "for the directory holding the tool.";

    private static string UnmarkedRootSentence(string declined) =>
        $"Deguffer found {declined} but it does not hold vcpkg's own '{VcpkgDiscovery.RootMarker}' "
        + "marker, so it did not look inside it. The buildtrees, downloads and packages directories of "
        + "a vcpkg clone are not covered here.";

    /// <summary>
    /// The declarations this machine's layout produces: up to three roots, because the binary cache,
    /// the clone and a relocated downloads directory each move independently and may end up in three
    /// different places.
    /// </summary>
    private IReadOnlyList<DeclaredRoot> Declare(VcpkgLocations located, List<string>? refused = null)
    {
        var roots = new List<DeclaredRoot>(3);

        // The three locations move independently and nothing stops two of them arriving at one
        // directory — a binary cache pointed at the clone's own downloads, or both variables set to
        // one "put all the vcpkg junk here" folder. Declared twice, that directory becomes two steps
        // over one path: its size is counted twice in the total the user reads, and §5.6 reports one
        // survivor as two.
        var declared = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        if (Containing(
                located.BinaryCache,
                "Binaries vcpkg built earlier and kept so it would not build them again. Removing one "
                + "means the next install of that library builds it from source.",
                located,
                refused) is { } binaryCache)
        {
            declared.Add(located.BinaryCache!);
            roots.Add(binaryCache);
        }

        if (located.Root is { } root)
        {
            var locations = new List<DeclaredLocation>(3)
            {
                new("buildtrees",
                    "Intermediate build output, one directory per port. vcpkg re-creates what it needs on the next build."),
                new("packages",
                    "The staging area a built port is assembled in before it is installed. It is re-created per build."),
            };

            if (located.RelocatedDownloads is null)
            {
                locations.Add(new DeclaredLocation(
                    "downloads",
                    "Source archives and the tools vcpkg downloaded to build with. It fetches each one again when a build needs it."));
            }

            locations.RemoveAll(l => !declared.Add(Path.Combine(root, l.RelativePath)));

            roots.Add(new DeclaredRoot(
                root,
                "The vcpkg directory itself must survive — it is never listed and never a target, and only "
                + "the paths named inside it are removed.",
                RequiresElevation: false,
                locations,
                ProtectedInRoot));
        }

        if (located.RelocatedDownloads is { } relocated
            && declared.Add(relocated)
            && Containing(
                relocated,
                "Source archives and the tools vcpkg downloaded to build with. It fetches each one again when a build needs it.",
                located,
                refused)
                is { } downloads)
        {
            roots.Add(downloads);
        }

        return roots;
    }

    /// <summary>
    /// One whole directory declared as a location of the directory that holds it, which is how a
    /// path the user relocated still gets §5.2's "the parent is never a target" and §5.6's
    /// assertion that it survived.
    ///
    /// Null when there is no containing directory — a cache pointed at a volume root — because
    /// declaring a volume as the root Deguffer reaches into is not a thing this should do.
    /// </summary>
    private DeclaredRoot? Containing(
        string? path,
        string reason,
        VcpkgLocations located,
        List<string>? refused)
    {
        if (path is null)
        {
            return null;
        }

        if (Path.GetDirectoryName(path) is not { Length: > 0 } container || IsToolsOwn(path, located))
        {
            refused?.Add(path);

            return null;
        }

        // Either of the user's vcpkg directories, because the documented search order falls through
        // from the local profile to the roaming one — and a cache found under the second still has
        // that second directory's own records sitting beside it.
        var inProfile = _discovery.ProfileDirectories.Contains(container, StringComparer.OrdinalIgnoreCase);

        return new DeclaredRoot(
            container,
            inProfile
                ? "The user's vcpkg directory must survive — only the cache inside it is removed."
                : "The directory holding this cache must survive — only the cache inside it is removed.",
            RequiresElevation: false,
            [new DeclaredLocation(Path.GetFileName(path), reason)],
            inProfile ? ProtectedInProfile : []);
    }

    /// <summary>
    /// Whether a configured cache path is really part of vcpkg rather than a cache of it.
    ///
    /// <para>§5.2, in the two forms Maven needed. A variable pointed <em>at</em> the clone or at one
    /// of the user's own vcpkg directories would make that directory a whole-tree target, taking
    /// <c>installed</c> with it. A variable pointed <em>inside</em> one, at something this provider
    /// names as a survivor, is worse in a quieter way: the same plan would target it and assert it
    /// survived, which is the contradiction §5.6 exists to catch rather than to produce.</para>
    ///
    /// <para>The unmarked candidate counts as the clone too. Declining the marker is a reason to
    /// reach less far into a directory somebody named as vcpkg's, never a licence to remove the
    /// whole of it — and with no marker there is no declaration naming <c>installed</c> a survivor,
    /// so §5.6 would pass while it went.</para>
    /// </summary>
    private bool IsToolsOwn(string path, VcpkgLocations located)
    {
        foreach (var (directory, protectedNames) in ToolDirectories(located))
        {
            if (LongPath.Contains(path, directory)
                || protectedNames.Any(n => LongPath.Contains(Path.Combine(directory, n.RelativePath), path)))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>vcpkg's own directories on this machine, each with what it holds that must survive.</summary>
    private IEnumerable<(string Directory, (string RelativePath, string Reason)[] Protected)> ToolDirectories(
        VcpkgLocations located)
    {
        if ((located.Root ?? located.UnmarkedRoot) is { } clone)
        {
            yield return (clone, ProtectedInRoot);
        }

        foreach (var profile in _discovery.ProfileDirectories)
        {
            yield return (profile, ProtectedInProfile);
        }
    }

    /// <summary>
    /// Every path these declarations could target, so answering "is there anything here?" costs one
    /// existence check each and can never reach anything the declaration does not name.
    /// </summary>
    private static IEnumerable<string> DeclaredPaths(IReadOnlyList<DeclaredRoot> roots) =>
        from root in roots
        from location in root.Locations
        select Path.Combine(root.Path, location.RelativePath);
}
