using Deguffer.Core.Execution;
using Deguffer.Core.Safety;
using Deguffer.Core.Scanning;

namespace Deguffer.Core.Providers;

/// <summary>
/// vcpkg's binary cache and the scratch directories its builds leave behind. Researched rather than
/// measured: no vcpkg installation was present on the machine this was written against.
///
/// <para><b>Tier 2, because restoring one of these is a compile rather than a download.</b> vcpkg
/// builds every port from source, and the binary cache is what stops it doing that twice. Deleting
/// an entry costs the next install the whole build of that library, which for something the size of
/// Boost or Qt is tens of minutes to hours — §3's "re-created, but only by re-downloading gigabytes
/// or re-indexing for minutes", with the clock running the other way. Two of the four directories
/// here are genuinely scratch and would be Tier 1 alone, but a plan carries one tier and the more
/// cautious of the two governs it. The user is never denied them: selection is per step, so the
/// scratch can be taken and the cache left.</para>
///
/// <para><b>§5.1 was asked and there is no eviction command.</b> vcpkg's own answer to a cache that
/// has grown too large is the <c>--clean-after-build</c> family of flags on <c>vcpkg install</c>,
/// which cleans as it goes rather than afterwards, and its documentation says outright that
/// <c>buildtrees</c>, <c>downloads</c> and <c>packages</c> under the root are safe to delete. So
/// path deletion here is the vendor's own recommendation rather than a workaround.</para>
///
/// <para><b>This provider may see one location or four, and it says which.</b> The binary cache is
/// in the user's profile and is findable on any machine. The other three live inside the vcpkg
/// clone — a git checkout the user put wherever they liked — which is knowable only from
/// <c>VCPKG_ROOT</c>, from the file <c>vcpkg integrate install</c> wrote, or from the executable on
/// <c>PATH</c>. Where none of those answers, the plan carries a sentence saying so. A provider that
/// silently reported a fraction of a cache would be worse than one that names the part it could not
/// reach.</para>
///
/// <para><b>§5.2's trap here is the largest directory of the lot.</b> <c>installed</c> sits in the
/// same root as the three scratch directories, it is regenerated by exactly the command that fills
/// them, and it is what every project on the machine links against. It is never enumerated and
/// never a target — this provider names the paths it removes rather than listing the clone, which
/// is what <see cref="DeclaredRoot"/> is for — and it is a named survivor, so a run produces
/// evidence rather than an absence of mention.</para>
/// </summary>
public sealed class VcpkgCacheProvider : CleanupProviderBase
{
    /// <summary>
    /// What the vcpkg clone holds that must survive a rule reaching into it. <c>installed</c> is
    /// the reason this list exists; the rest are the clone itself, and losing any of them means
    /// re-cloning rather than rebuilding.
    /// </summary>
    private static readonly (string RelativePath, string Reason)[] ProtectedInRoot =
    [
        ("installed", "The libraries vcpkg has installed, which every project on this machine links against."),
        ("ports", "The port definitions this clone builds from."),
        ("triplets", "The triplet definitions, including any the user wrote."),
        ("versions", "The registry's version database."),
        ("scripts", "vcpkg's own build scripts."),
        ("vcpkg.exe", "The vcpkg executable itself, which the bootstrap built into this directory."),
    ];

    /// <summary>
    /// What the user's vcpkg directory holds beside the binary cache. Both are small, and both are
    /// records rather than caches: one says where the clone is, and the other holds the registry
    /// clones a manifest resolves against.
    /// </summary>
    private static readonly (string RelativePath, string Reason)[] ProtectedInProfile =
    [
        (VcpkgDiscovery.IntegrationFile, "vcpkg's record of which clone is integrated with Visual Studio."),
        ("registries", "Clones of the registries a manifest resolves versions against."),
    ];

    private readonly VcpkgDiscovery _discovery;

    public VcpkgCacheProvider(
        IUserEnvironment? environment = null,
        IProcessRunner? runner = null,
        IProcessInspector? inspector = null,
        IDirectoryScanner? scanner = null)
        : base(
            environment ?? UserEnvironment.Current,
            runner ?? ProcessRunner.Default,
            inspector ?? ProcessInspector.Default,
            scanner ?? DirectoryScanner.Default)
        => _discovery = new VcpkgDiscovery(Environment);

    public override string Id => "vcpkg";

    public override string Name => "vcpkg build caches";

    public override SafetyTier Tier => SafetyTier.RegenerableWithCost;

    public override string WhatHappensOnNextUse =>
        "The next vcpkg install rebuilds the affected libraries from source instead of unpacking a "
        + "cached binary, which for a large library is tens of minutes, and downloads their source "
        + "archives again as it goes. Libraries already installed stay installed, and the ports, "
        + "triplets and registries are untouched.";

    /// <summary>
    /// §5.3. Only vcpkg's own name, deliberately: the compilers and build tools it drives are the
    /// user's everyday ones, so warning on those would fire on almost every scan, and a warning
    /// that is always there is one nobody reads.
    /// </summary>
    protected override IReadOnlyList<string> ConflictingProcessNames => ["vcpkg"];

    /// <summary>Where vcpkg's directories are on this machine. Exposed so tests can assert what is reached.</summary>
    public VcpkgLocations Locate() => _discovery.Discover();

    /// <summary>
    /// Presence is a declared path actually being there. The user's vcpkg directory exists on any
    /// machine that has ever integrated vcpkg with Visual Studio, and reading that as a hit would
    /// report a source the plan then has nothing to say about.
    /// </summary>
    public override Task<bool> IsPresentAsync(CancellationToken ct = default) =>
        Task.FromResult(DeclaredPaths(Declare(Locate())).Any(LongPath.DirectoryExists));

    public override async Task<CleanupPlan> PlanAsync(CancellationToken ct = default)
    {
        var located = Locate();
        var scan = DeclaredLocations.Examine(Declare(located), ct);

        if (scan.FoundNothing)
        {
            return EmptyPlan("vcpkg has cached nothing on this machine.");
        }

        var notes = new List<PlanNote>(scan.Notes);

        if (located.Root is null)
        {
            // Said whenever the clone was not found, not only when something was reclaimed without
            // it. The user is looking at a number, and the number is a quarter of the subject.
            notes.Add(new PlanNote(
                PlanNoteSeverity.Information,
                "This covers the binary cache only. vcpkg's own directory is a clone that can be anywhere, "
                + $"and Deguffer could not find it — set {VcpkgDiscovery.RootVariable}, or put vcpkg on PATH, "
                + "and the buildtrees, downloads and packages directories inside it are covered too."));
        }

        var (steps, measured) = await PlanDeletionsAsync(scan.Targets, ct).ConfigureAwait(false);

        if (measured.Note is { } scanNote)
        {
            notes.Add(scanNote);
        }

        if (BuildRunningProcessNote() is { } warning)
        {
            notes.Add(warning);
        }

        return new CleanupPlan
        {
            ProviderId = Id,
            ProviderName = Name,
            Tier = Tier,
            WhatHappensOnNextUse = WhatHappensOnNextUse,
            Steps = steps,
            ProtectedPaths = Protect([.. scan.Protected]),
            Notes = notes,
            Fallback = measured.Fallback,
        };
    }

    /// <summary>
    /// The declarations this machine's layout produces: up to three roots, because the binary cache,
    /// the clone and a relocated downloads directory each move independently and may end up in three
    /// different places.
    /// </summary>
    private IReadOnlyList<DeclaredRoot> Declare(VcpkgLocations located)
    {
        var roots = new List<DeclaredRoot>(3);

        if (Containing(
                located.BinaryCache,
                "Binaries vcpkg built earlier and kept so it would not build them again. Removing one "
                + "means the next install of that library builds it from source.") is { } binaryCache)
        {
            roots.Add(binaryCache);
        }

        if (located.Root is { } root)
        {
            var locations = new List<DeclaredLocation>(3)
            {
                new("buildtrees",
                    "Intermediate build output, one directory per port. vcpkg re-creates what it needs on the next build."),
                new("packages",
                    "The staging area a built port is assembled in before it is installed. It is re-created per build."),
            };

            if (located.RelocatedDownloads is null)
            {
                locations.Add(new DeclaredLocation(
                    "downloads",
                    "Source archives and the tools vcpkg downloaded to build with. It fetches each one again when a build needs it."));
            }

            roots.Add(new DeclaredRoot(
                root,
                "The vcpkg directory itself must survive — it is never listed and never a target, and only "
                + "the paths named inside it are removed.",
                RequiresElevation: false,
                locations,
                ProtectedInRoot));
        }

        if (Containing(
                located.RelocatedDownloads,
                "Source archives and the tools vcpkg downloaded to build with. It fetches each one again when a build needs it.")
            is { } downloads)
        {
            roots.Add(downloads);
        }

        return roots;
    }

    /// <summary>
    /// One whole directory declared as a location of the directory that holds it, which is how a
    /// path the user relocated still gets §5.2's "the parent is never a target" and §5.6's
    /// assertion that it survived.
    ///
    /// Null when there is no containing directory — a cache pointed at a volume root — because
    /// declaring a volume as the root Deguffer reaches into is not a thing this should do.
    /// </summary>
    private DeclaredRoot? Containing(string? path, string reason)
    {
        if (path is null || Path.GetDirectoryName(path) is not { Length: > 0 } container)
        {
            return null;
        }

        var inProfile = container.Equals(_discovery.ProfileDirectory, StringComparison.OrdinalIgnoreCase);

        return new DeclaredRoot(
            container,
            inProfile
                ? "The user's vcpkg directory must survive — only the cache inside it is removed."
                : "The directory holding this cache must survive — only the cache inside it is removed.",
            RequiresElevation: false,
            [new DeclaredLocation(Path.GetFileName(path), reason)],
            inProfile ? ProtectedInProfile : []);
    }

    /// <summary>
    /// Every path these declarations could target, so answering "is there anything here?" costs one
    /// existence check each and can never reach anything the declaration does not name.
    /// </summary>
    private static IEnumerable<string> DeclaredPaths(IReadOnlyList<DeclaredRoot> roots) =>
        from root in roots
        from location in root.Locations
        select Path.Combine(root.Path, location.RelativePath);
}
